Task 1: Creating Tensors

In [ ]:
import torch

list_tensor = torch.tensor([1, 2, 3, 4, 5])

zeros_tensor = torch.zeros((3, 3))

ones_tensor = torch.ones((2, 4))

rand_tensor = torch.rand((3, 3))

identity_tensor = torch.eye(3)

float_tensor = torch.tensor([1.5, 2.5], dtype=torch.float32)
int_tensor = torch.tensor([1, 2], dtype=torch.int64)

print("List tensor:", list_tensor)
print("Zeros:\n", zeros_tensor)
print("Ones:\n", ones_tensor)
print("Random:\n", rand_tensor)
print("Identity:\n", identity_tensor)
print("Float tensor dtype:", float_tensor.dtype)

List tensor: tensor([1, 2, 3, 4, 5])
Zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Ones:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Random:
 tensor([[0.0021, 0.5025, 0.0661],
        [0.2798, 0.4536, 0.4426],
        [0.3116, 0.6286, 0.8226]])
Identity:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Float tensor dtype: torch.float32


Task 2: Tensor Information

In [ ]:
t = torch.rand((3, 4, 2))

print("Shape (Shakli):", t.shape)
print("Data type (Ma'lumot turi):", t.dtype)
print("Device (Qurilma - CPU/GPU):", t.device)
print("Number of dimensions (O'lchamlar soni):", t.ndim)

Shape (Shakli): torch.Size([3, 4, 2])
Data type (Ma'lumot turi): torch.float32
Device (Qurilma - CPU/GPU): cpu
Number of dimensions (O'lchamlar soni): 3


Task 3: Tensor Operations

In [ ]:
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

add_res = a + b

mul_res = a * b

matmul_res = torch.matmul(a, b) # yoki a @ b

reshaped = a.reshape(1, 4)

flattened = a.flatten()

concat_res = torch.cat((a, b), dim=0)

print("Addition:\n", add_res)
print("Multiplication:\n", mul_res)
print("Matrix Multiplication:\n", matmul_res)
print("Reshaped:\n", reshaped)
print("Flattened:\n", flattened)
print("Concatenated:\n", concat_res)

Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])
Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])
Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])
Reshaped:
 tensor([[1., 2., 3., 4.]])
Flattened:
 tensor([1., 2., 3., 4.])
Concatenated:
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


Task 4: Indexing and Slicing

In [ ]:
grid = torch.tensor([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

single_elem = grid[1, 1] # 50

first_row = grid[0, :] # Birinchi satr

second_col = grid[:, 1] # Ikkinchi ustun

sub_grid = grid[0:2, 1:3]

grid[0, 0] = 999

print("Single Element:", single_elem.item())
print("First Row:", first_row)
print("Second Column:", second_col)
print("Sliced Grid:\n", sub_grid)
print("Modified Grid:\n", grid)

Single Element: 50
First Row: tensor([999,  20,  30])
Second Column: tensor([20, 50, 80])
Sliced Grid:
 tensor([[20, 30],
        [50, 60]])
Modified Grid:
 tensor([[999,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]])


Task 5: NumPy and Tensors

In [ ]:
import numpy as np

np_array = np.array([1, 2, 3, 4, 5])
tensor_from_np = torch.from_numpy(np_array)

tensor_data = torch.ones(3, 3)
np_from_tensor = tensor_data.numpy()

print("Tensor from NumPy:", tensor_from_np)
print("NumPy from Tensor:\n", np_from_tensor)

Tensor from NumPy: tensor([1, 2, 3, 4, 5])
NumPy from Tensor:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Task 6: Mini Challenge

In [ ]:
challenge_tensor = torch.rand(4, 5)

tensor_mean = challenge_tensor.mean()
tensor_max = challenge_tensor.max()
tensor_min = challenge_tensor.min()
tensor_sum = challenge_tensor.sum()

print("Random 4x5 Tensor:\n", challenge_tensor)
print(f"Mean: {tensor_mean.item():.4f}")
print(f"Max: {tensor_max.item():.4f}")
print(f"Min: {tensor_min.item():.4f}")
print(f"Sum: {tensor_sum.item():.4f}")

Random 4x5 Tensor:
 tensor([[0.4663, 0.8777, 0.5800, 0.9484, 0.2753],
        [0.8936, 0.4719, 0.3794, 0.7115, 0.6963],
        [0.2127, 0.7621, 0.9318, 0.2225, 0.2085],
        [0.9627, 0.4904, 0.1133, 0.3058, 0.6900]])
Mean: 0.5600
Max: 0.9627
Min: 0.1133
Sum: 11.2005


What is a tensor?

Tenzor — chuqur o'rganishda ishlatiladigan ko'p o mezonli sonlar matritsasi bo'lib, u skalyar ($0$D), vektor ($1$D) va matritsa ($2$D) kabi tushunchalarni yanada yuqori o'lchamlarga umumiylashtiruvchi ma'lumot tuzilmasidir.

Why are tensors important in deep learning?

Tenzorlar barcha turdagi ma'lumotlarni (rasmlar, matnlar, audiolar) neyron tarmoqlari tushunadigan shaklda saqlash va ular ustida GPU yordamida tezkor parallel matematik amallar bajarish imkonini bergani uchun muhim.

What is the difference between a tensor and a NumPy array?

Asosiy farqi — PyTorch tenzorlari GPU (grafik protsessorlar) da ishlashni hamda avtomatik hosila (Autograd) hisoblashni qo'llab-quvvatlaydi, NumPy ndarray esa faqat CPU'da ishlaydi va avtomatik hosila funksiyasiga ega emas.